services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=players
      - POSTGRES_USER=player_user
      - POSTGRES_PASSWORD=player_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  football-app:
    image: football-microservice:latest
    container_name: football-app
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/players
      - SPRING_DATASOURCE_USERNAME=player_user
      - SPRING_DATASOURCE_PASSWORD=player_password
    ports:
      - "9090:9090"
    depends_on:
      - postgres

volumes:
  postgres_data:
